# Config file aligning with the HS-TasNet paper [HS-TasNet Paper](https://arxiv.org/html/2402.17701v1)
audio:
  chunk_size: 1024 # 1024 samples ≈ 23 ms at 44100 Hz
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 0.001

model:
  num_sources: 4 # Typically: vocals, bass, drums, other
  num_channels: 2 # Must match audio.num_channels
  time_win_size: 1024 # Learned convolution branch window size (basis signals)
  time_hop_size: 512 # 50% overlap yields ~23 ms latency
  time_ftr_size: 1024 # Number of basis signals (as per paper)
  spec_win_size: 1024 # STFT window size for spectrogram branch (produces 513-dimensional features)
  spec_hop_size: 512 # Consistent with time branch for alignment
  spec_fft_size: 1024 # FFT size equals window size
  rnn_hidden_size: 1000 # Combined branch hidden dimension (500 per branch concatenated)
  rnn_num_layers: 2 # Each "Memory: LSTM" block uses 2 layers, following the paper

training:
  batch_size: 2 # Smaller batch size due to very short chunk length
  gradient_accumulation_steps: 8 # Increase effective batch size based on memory availability
  grad_clip: 0
  instruments:
    - vocals
    - bass
    - drums
    - other
  lr: 1.0e-04
  patience: 3
  reduce_factor: 0.95
  target_instrument: null
  num_epochs: 1000
  num_steps: 1000
  q: 0.95
  coarse_loss_clip: true
  ema_momentum: 0.999
  optimizer: adam
  other_fix: false
  use_amp: true

augmentations:
  enable: true
  loudness: true
  loudness_min: 0.8
  loudness_max: 1.2
  mixup: true
  mixup_probs: [0.2, 0.02]
  mixup_loudness_min: 0.8
  mixup_loudness_max: 1.2
  all:
    channel_shuffle: 0.5
    random_inverse: 0.1
    random_polarity: 0.5

inference:
  batch_size: 1
  num_overlap: 1 # Minimal overlap for truly low-latency processing
